---
title: "Reading Data"
author: "Shengnan Sun"
date: "2017-10-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load package}
library(tidyverse)
library(rvest)
library(httr)
```

## Scraping

### NSDUH Table

```{r get the webset}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_xml = read_html(url)
```

```{r get all tables}
drug_use_xml %>%
  html_nodes(css = "table") # extract everything with mode table
```

```{r get the table we want}
table_marj = (drug_use_xml %>% html_nodes(css = "table"))[[1]] %>% #[[1]] first object of the first list
  html_table() %>% # convert to useful formate
  .[-1,] %>%# remove the first row
  as_tibble()
```

### NY living cost table

```{r practice}
ny_living_cost = read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york")
ny_living_cost %>%
  html_nodes(css = "table")
living_cost = (ny_living_cost %>% html_nodes(css = "table"))[[2]] %>%
  html_table(header = TRUE) %>%
  as_tibble() 
```

## HP_SS cast

Want the names!
```{r}
hpss_html = read_html("http://www.imdb.com/title/tt0241527/")

hpss_cast = hpss_html %>%
  html_nodes(css = ".itemprop .itemprop") %>%
  html_text()
```


### Toothbrush reviews

Deantal hygiene;;ksdf

```{r}
toothbrush_xml = read_html("https://www.amazon.com/Philips-Sonicare-rechargeable-toothbrush-HX6211/product-reviews/B00YAR7ZFM/ref=cm_cr_arp_d_viewopt_srt?ie=UTF8&reviewerType=all_reviews&sortBy=recent&pageNumber=1")

toothbrush_titles = toothbrush_xml %>%
  html_nodes(css = "#cm_cr-review_list .a-color-base") %>% #using SelectorGadget
  html_text()

toothbrush_stars = toothbrush_xml %>%
  html_nodes(css = "#cm_cr-review_list .review-rating") %>% #using SelectorGadget
  html_text()

toothbrush_df = data_frame(
  title = toothbrush_titles,
  stars = toothbrush_stars
)
```


##API

### Water use data

https://data.cityofnewyork.us/resource/waf7-5gvc.csv
